[[redirects]]
    from = "/modern/NOOK_ALLEY.webm"
    to = "/videos/legacy/NOOK_ALLEY.webm"
    status = 200
    force = true

[[redirects]]
    from = "/modern/NOOK_ALLEY.mp4"
    to = "/videos/legacy/NOOK_ALLEY.mp4"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "/pages/404.html"
    status = 404